-- ============================================================
-- TEMPLATE BASE - CONCESSIONÁRIA IA
-- Execute este script em cada novo projeto Supabase
-- Ordem correta: funções → tabelas sem FK → tabelas com FK → índices → triggers → permissões
-- ============================================================

-- ------------------------------------------------------------
-- LIMPEZA PRÉVIA (ordem reversa de FK para evitar conflitos)
-- ------------------------------------------------------------

DROP TABLE IF EXISTS public."HISTORICO_VISITAS"  CASCADE;
DROP TABLE IF EXISTS public."AGENDAMENTOS"        CASCADE;
DROP TABLE IF EXISTS public."BASE_DE_LEADS"       CASCADE;
DROP TABLE IF EXISTS public."VENDEDORES"          CASCADE;
DROP TABLE IF EXISTS public."AUTORIZAÇÃO"         CASCADE;
DROP TABLE IF EXISTS public."HISTORICO_CHAT"      CASCADE;
DROP TABLE IF EXISTS public."ESTOQUE"             CASCADE;

-- tabelas com nomes antigos (caso existam de versões anteriores)
DROP TABLE IF EXISTS public.ac_chat_histories     CASCADE;
DROP TABLE IF EXISTS public.estoque               CASCADE;


-- ------------------------------------------------------------
-- FUNÇÕES AUXILIARES (precisam existir antes dos triggers)
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION check_admin_exists()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'DELETE' OR (TG_OP = 'UPDATE' AND NEW.cargo != 'administrador')) THEN
    IF OLD.cargo = 'administrador' AND (
      SELECT COUNT(*) FROM public."AUTORIZAÇÃO"
      WHERE cargo = 'administrador'
        AND id_empresa = OLD.id_empresa
        AND id != OLD.id
    ) = 0 THEN
      RAISE EXCEPTION 'Não é possível remover o último administrador da empresa.';
    END IF;
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;


-- ------------------------------------------------------------
-- 1. AUTORIZAÇÃO
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."AUTORIZAÇÃO" (
  id                serial                      NOT NULL,
  id_empresa        integer                     NOT NULL,
  nome_empresa      character varying(255)      NOT NULL,
  nome_usuario      character varying(255)      NOT NULL,
  email             character varying(255)      NOT NULL,
  senha             character varying(255)      NOT NULL,
  telefone          character varying(20)       NULL,
  plano             character varying(50)       NULL DEFAULT 'gratuito'::character varying,
  status            character varying(20)       NULL DEFAULT 'ativo'::character varying,
  created_at        timestamp without time zone NULL DEFAULT now(),
  updated_at        timestamp without time zone NULL DEFAULT now(),
  cargo             character varying(20)       NULL DEFAULT 'convidado'::character varying,
  CONSTRAINT "AUTORIZAÇÃO_pkey"       PRIMARY KEY (id),
  CONSTRAINT "AUTORIZAÇÃO_email_key"  UNIQUE (email),
  CONSTRAINT "AUTORIZAÇÃO_cargo_check" CHECK (
    (cargo)::text = ANY ((ARRAY[
      'administrador'::character varying,
      'convidado'::character varying
    ])::text[])
  ),
  CONSTRAINT "AUTORIZAÇÃO_status_check" CHECK (
    (status)::text = ANY ((ARRAY[
      'ativo'::character varying,
      'pendente'::character varying,
      'inativo'::character varying
    ])::text[])
  )
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_autorizacao_email_status    ON public."AUTORIZAÇÃO" USING btree (email, status)      TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_autorizacao_empresa_status  ON public."AUTORIZAÇÃO" USING btree (id_empresa, status)  TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_autorizacao_empresa_cargo   ON public."AUTORIZAÇÃO" USING btree (id_empresa, cargo)   TABLESPACE pg_default;

CREATE TRIGGER protect_last_admin
  BEFORE DELETE OR UPDATE ON public."AUTORIZAÇÃO"
  FOR EACH ROW EXECUTE FUNCTION check_admin_exists();


-- ------------------------------------------------------------
-- 2. VENDEDORES
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."VENDEDORES" (
  id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at    timestamp with time zone                NOT NULL DEFAULT now(),
  vendedor      character varying                       NULL,
  telefone      character varying                       NULL,
  atender       text                                    NULL,
  quantos_lead  integer                                  NULL,
  id_click      text                                    NULL,
  id_empresa    character varying                       NULL,
  CONSTRAINT "VENDEDORES_pkey" PRIMARY KEY (id)
) TABLESPACE pg_default;


-- ------------------------------------------------------------
-- 3. BASE_DE_LEADS
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."BASE_DE_LEADS" (
  id                      serial                      NOT NULL,
  id_empresa              integer                     NOT NULL,
  nome_lead               character varying(255)      NOT NULL,
  telefone                character varying(20)       NULL,
  email                   character varying(255)      NULL,
  origem                  character varying(100)      NULL,
  vendedor                character varying(255)      NULL,
  veiculo_interesse       character varying(255)      NULL,
  resumo_qualificacao     text                        NULL,
  estagio_lead            character varying(50)       NULL DEFAULT 'oportunidade'::character varying,
  resumo_comercial        text                        NULL,
  created_at              timestamp without time zone NULL DEFAULT now(),
  updated_at              timestamp without time zone NULL DEFAULT now(),
  valor                   numeric(15, 2)              NULL DEFAULT 0.00,
  observacao_vendedor     text                        NULL DEFAULT ''::text,
  bot_ativo               character varying           NULL,
  "Etapa"                  character varying           NULL,
  "QuemEnviouMsg"          character varying           NULL,
  "UltimaMensagem"         character varying           NULL,
  "Status de Follow"       character varying           NULL,
  "Transferencia"          character varying           NULL,
  "Pesquisa de satisfação" character varying           NULL,
  "ID CONTATO CLICK"       character varying           NULL,
  lid                      character varying           NULL,
  "Data e Hora"            character varying           NULL,
  CONSTRAINT "BASE_DE_LEADS_pkey" PRIMARY KEY (id),
  CONSTRAINT "BASE_DE_LEADS_estagio_lead_check" CHECK (
    (estagio_lead)::text = ANY ((ARRAY[
      'oportunidade'::character varying,
      'em_qualificacao'::character varying,
      'em_negociacao'::character varying,
      'fechado'::character varying,
      'nao_fechou'::character varying,
      'pesquisa_atendimento'::character varying,
      'follow_up'::character varying
    ])::text[])
  )
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_base_leads_valor      ON public."BASE_DE_LEADS" USING btree (valor)                       TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_base_leads_observacao ON public."BASE_DE_LEADS" USING btree (id_empresa, observacao_vendedor) TABLESPACE pg_default;


-- ------------------------------------------------------------
-- 4. AGENDAMENTOS  (FK → BASE_DE_LEADS, VENDEDORES)
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."AGENDAMENTOS" (
  id                   serial                      NOT NULL,
  id_empresa           integer                     NOT NULL,
  id_lead              integer                     NOT NULL,
  nome_lead            character varying(255)      NOT NULL,
  telefone             character varying(20)       NULL,
  email                character varying(255)      NULL,
  modelo_veiculo       character varying(255)      NULL,
  data_agendamento     date                        NULL,
  hora_agendamento     time without time zone      NULL,
  vendedor             character varying(255)      NULL,
  id_vendedor          integer                     NULL,
  estagio_agendamento  character varying(50)       NULL DEFAULT 'agendar'::character varying,
  observacoes          text                        NULL,
  created_at           timestamp without time zone NULL DEFAULT now(),
  updated_at           timestamp without time zone NULL DEFAULT now(),
  data_acao            timestamp without time zone NULL,
  usuario_acao         character varying(255)      NULL,
  motivo_nao_fechou    text                        NULL,
  status               character varying           NULL,
  CONSTRAINT "AGENDAMENTOS_pkey"         PRIMARY KEY (id),
  CONSTRAINT "AGENDAMENTOS_id_lead_fkey" FOREIGN KEY (id_lead)     REFERENCES public."BASE_DE_LEADS" (id) ON DELETE CASCADE,
  CONSTRAINT "AGENDAMENTOS_id_vendedor_fkey" FOREIGN KEY (id_vendedor) REFERENCES public."VENDEDORES" (id),
  CONSTRAINT "AGENDAMENTOS_estagio_agendamento_check" CHECK (
    (estagio_agendamento)::text = ANY ((ARRAY[
      'agendar'::character varying,
      'agendado'::character varying,
      'realizou_visita'::character varying,
      'fechou'::character varying,
      'nao_fechou'::character varying
    ])::text[])
  )
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_agendamentos_id_empresa ON public."AGENDAMENTOS" USING btree (id_empresa)           TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_agendamentos_id_lead    ON public."AGENDAMENTOS" USING btree (id_lead)              TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_agendamentos_estagio    ON public."AGENDAMENTOS" USING btree (estagio_agendamento)  TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_agendamentos_data       ON public."AGENDAMENTOS" USING btree (data_agendamento)     TABLESPACE pg_default;


-- ------------------------------------------------------------
-- 5. HISTORICO_VISITAS  (FK → AGENDAMENTOS, BASE_DE_LEADS)
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."HISTORICO_VISITAS" (
  id               serial                      NOT NULL,
  id_empresa       integer                     NOT NULL,
  id_agendamento   integer                     NOT NULL,
  id_lead          integer                     NOT NULL,
  nome_lead        character varying(255)      NOT NULL,
  telefone         character varying(20)       NULL,
  vendedor         character varying(255)      NULL,
  data_agendamento date                        NULL,
  hora_agendamento time without time zone      NULL,
  status_visita    character varying(50)       NOT NULL,
  data_hora_acao   timestamp without time zone NOT NULL,
  usuario_acao     character varying(255)      NULL,
  motivo           text                        NULL,
  created_at       timestamp without time zone NULL DEFAULT now(),
  CONSTRAINT "HISTORICO_VISITAS_pkey"                PRIMARY KEY (id),
  CONSTRAINT "HISTORICO_VISITAS_id_agendamento_fkey" FOREIGN KEY (id_agendamento) REFERENCES public."AGENDAMENTOS"  (id) ON DELETE CASCADE,
  CONSTRAINT "HISTORICO_VISITAS_id_lead_fkey"        FOREIGN KEY (id_lead)        REFERENCES public."BASE_DE_LEADS" (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_historico_visitas_empresa ON public."HISTORICO_VISITAS" USING btree (id_empresa)    TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_historico_visitas_data    ON public."HISTORICO_VISITAS" USING btree (data_hora_acao) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_historico_visitas_status  ON public."HISTORICO_VISITAS" USING btree (status_visita)  TABLESPACE pg_default;


-- ------------------------------------------------------------
-- 6. HISTORICO_CHAT
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."HISTORICO_CHAT" (
  id         serial                 NOT NULL,
  session_id character varying(255) NOT NULL,
  message    jsonb                  NOT NULL,
  CONSTRAINT "HISTORICO_CHAT_pkey" PRIMARY KEY (id)
) TABLESPACE pg_default;


-- ------------------------------------------------------------
-- 7. ESTOQUE
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."ESTOQUE" (
  id             serial                   NOT NULL,
  marca          character varying(100)   NOT NULL,
  modelo         character varying(100)   NOT NULL,
  ano            integer                  NOT NULL,
  cor            character varying(50)    NOT NULL,
  combustivel    character varying(50)    NOT NULL,
  quilometragem  integer                  NOT NULL,
  status         character varying(20)    NULL DEFAULT 'Disponível'::character varying,
  created_at     timestamp with time zone NULL DEFAULT now(),
  updated_at     timestamp with time zone NULL DEFAULT now(),
  placa          text                     NULL,
  "link imagem 0" character varying       NULL,
  valor          character varying        NULL,
  motor          text                     NULL,
  "link imagem 1" character varying       NULL,
  "link imagem 2" character varying       NULL,
  "link imagem 3" character varying       NULL,
  "ID VEICULO"   character varying        NULL,
  tipo           character varying        NULL,
  CONSTRAINT "ESTOQUE_pkey" PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_estoque_marca   ON public."ESTOQUE" USING btree (marca)  TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_estoque_modelo  ON public."ESTOQUE" USING btree (modelo) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_estoque_status  ON public."ESTOQUE" USING btree (status) TABLESPACE pg_default;

CREATE TRIGGER update_estoque_updated_at
  BEFORE UPDATE ON public."ESTOQUE"
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ============================================================
-- PERMISSÕES E RLS — liberação para chamadas do n8n
-- Executa por último, depois de todas as tabelas criadas
-- ============================================================

DO $$
DECLARE
    r RECORD;
BEGIN
    -- 1. Concede permissões em todas as tabelas atuais para o n8n
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO authenticated;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO service_role;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
    -- 2. Concede permissões em todas as sequências atuais (IDs automáticos)
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO authenticated;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO service_role;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;
    -- 3. Desativa o RLS de absolutamente todas as tabelas para ficarem "UNRESTRICTED"
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE 'ALTER TABLE public.' || quote_ident(r.tablename) || ' DISABLE ROW LEVEL SECURITY;';
    END LOOP;
END $$;

-- 4. Garante que qualquer NOVA tabela criada no futuro já nasça com permissão total
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO postgres;


-- ============================================================
-- CAMADA UNIVERSAL DO CRM AUTOMOTIVO - MIGRATIONS CONSOLIDADAS EM 27/07/2026
-- Não executar novamente as migrations separadas em um banco criado por este arquivo.
-- ============================================================


-- ===== 0001_init.sql =====

-- EazyClick CRM — migração inicial
--
-- IMPORTANTE: as tabelas BASE_DE_LEADS, VENDEDORES, ESTOQUE, AGENDAMENTOS, HISTORICO_VISITAS,
-- HISTORICO_CHAT e "AUTORIZAÇÃO" já existem no banco (criadas por outro fluxo/automação) e NÃO
-- são recriadas aqui. Esta migração cuida apenas da camada de autenticação/autorização e das
-- tabelas de suporte do próprio CRM (profiles, app_settings, etiquetas).

-- =========================================================================
-- profiles
-- =========================================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text,
  email text,
  cargo text not null default 'vendedor' check (cargo in ('admin_master', 'gerente', 'vendedor')),
  created_at timestamptz default now()
);

-- Function auxiliar de RLS: retorna o cargo do usuário logado.
-- É SECURITY DEFINER para poder ler a tabela profiles sem disparar novamente as policies de
-- profiles (evitando recursão infinita: a policy de profiles chamaria get_my_cargo(), que por
-- sua vez consultaria profiles, que aplicaria a policy de novo, e assim por diante).
create or replace function public.get_my_cargo()
returns text
language sql
security definer
set search_path = public
stable
as $$
  select cargo from public.profiles where id = auth.uid();
$$;

-- Trigger: cria automaticamente um registro em profiles (e, se vendedor, também em VENDEDORES)
-- sempre que um novo usuário é criado em auth.users.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cargo text;
begin
  v_cargo := coalesce(new.raw_user_meta_data->>'cargo', 'vendedor');

  insert into public.profiles (id, nome, email, cargo)
  values (
    new.id,
    new.raw_user_meta_data->>'nome',
    new.email,
    v_cargo
  );

  if v_cargo = 'vendedor' then
    insert into public."VENDEDORES" (vendedor, telefone, id_empresa, quantos_lead)
    values (
      new.raw_user_meta_data->>'nome',
      new.raw_user_meta_data->>'telefone',
      null,
      0
    );
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- =========================================================================
-- app_settings (linha única de configuração, ex: token da uazapi)
-- =========================================================================
create table if not exists public.app_settings (
  id int primary key default 1,
  uazapi_token text,
  uazapi_base_url text not null default 'https://eazytech.uazapi.com',
  updated_at timestamptz default now(),
  constraint single_row check (id = 1)
);

insert into public.app_settings (id, uazapi_base_url)
values (1, 'https://eazytech.uazapi.com')
on conflict (id) do nothing;

-- =========================================================================
-- etiquetas
-- =========================================================================
create table if not exists public.etiquetas (
  id bigserial primary key,
  nome text not null,
  cor text not null default '#888888',
  created_at timestamptz default now()
);

-- =========================================================================
-- RLS
-- =========================================================================
alter table public.profiles enable row level security;
alter table public.app_settings enable row level security;
alter table public.etiquetas enable row level security;

-- profiles: qualquer usuário autenticado pode listar todos os perfis (necessário para telas
-- como "Leads por Vendedor", seleção de vendedor em formulários, fila de atendimento etc).
drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
  on public.profiles for select
  to authenticated
  using (true);

-- profiles: update permitido no próprio registro, OU por quem tem cargo admin_master/gerente.
drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin"
  on public.profiles for update
  to authenticated
  using (
    id = auth.uid()
    or public.get_my_cargo() in ('admin_master', 'gerente')
  );

-- app_settings: select/update restritos a admin_master.
drop policy if exists "app_settings_select_admin" on public.app_settings;
create policy "app_settings_select_admin"
  on public.app_settings for select
  to authenticated
  using (public.get_my_cargo() = 'admin_master');

drop policy if exists "app_settings_update_admin" on public.app_settings;
create policy "app_settings_update_admin"
  on public.app_settings for update
  to authenticated
  using (public.get_my_cargo() = 'admin_master');

-- etiquetas: select para todos autenticados, escrita restrita a admin_master/gerente.
drop policy if exists "etiquetas_select_authenticated" on public.etiquetas;
create policy "etiquetas_select_authenticated"
  on public.etiquetas for select
  to authenticated
  using (true);

drop policy if exists "etiquetas_insert_admin_gerente" on public.etiquetas;
create policy "etiquetas_insert_admin_gerente"
  on public.etiquetas for insert
  to authenticated
  with check (public.get_my_cargo() in ('admin_master', 'gerente'));

drop policy if exists "etiquetas_update_admin_gerente" on public.etiquetas;
create policy "etiquetas_update_admin_gerente"
  on public.etiquetas for update
  to authenticated
  using (public.get_my_cargo() in ('admin_master', 'gerente'));

drop policy if exists "etiquetas_delete_admin_gerente" on public.etiquetas;
create policy "etiquetas_delete_admin_gerente"
  on public.etiquetas for delete
  to authenticated
  using (public.get_my_cargo() in ('admin_master', 'gerente'));


-- ===== 0002_rls_dados_operacionais.sql =====

-- EazyClick CRM — RLS para as tabelas operacionais pré-existentes (BASE_DE_LEADS, VENDEDORES,
-- ESTOQUE). Essas tabelas já existiam no banco (criadas por outro fluxo/automação) com RLS
-- habilitado e sem nenhuma policy, o que bloqueia qualquer leitura/escrita via PostgREST mesmo
-- para usuários autenticados (a query retorna vazio, sem erro). Como o CRM é single-tenant e
-- todo usuário autenticado é um funcionário interno confiável, liberamos acesso total para o
-- role "authenticated".

alter table public."BASE_DE_LEADS" enable row level security;
alter table public."VENDEDORES" enable row level security;
alter table public."ESTOQUE" enable row level security;

drop policy if exists "base_de_leads_all_authenticated" on public."BASE_DE_LEADS";
create policy "base_de_leads_all_authenticated"
  on public."BASE_DE_LEADS" for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "vendedores_all_authenticated" on public."VENDEDORES";
create policy "vendedores_all_authenticated"
  on public."VENDEDORES" for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "estoque_all_authenticated" on public."ESTOQUE";
create policy "estoque_all_authenticated"
  on public."ESTOQUE" for all
  to authenticated
  using (true)
  with check (true);


-- ===== 0003_lead_detalhes.sql =====

-- EazyClick CRM — campos adicionais de detalhe do lead (ficha exibida no drawer do Pipeline)
-- e tabela de vínculo N:N entre leads e etiquetas.

alter table public."BASE_DE_LEADS"
  add column if not exists cpf varchar,
  add column if not exists data_nascimento date,
  add column if not exists score_serasa integer;

create table if not exists public.lead_etiquetas (
  id bigserial primary key,
  id_lead int4 not null references public."BASE_DE_LEADS"(id) on delete cascade,
  id_etiqueta bigint not null references public.etiquetas(id) on delete cascade,
  created_at timestamptz default now(),
  unique (id_lead, id_etiqueta)
);

alter table public.lead_etiquetas enable row level security;

drop policy if exists "lead_etiquetas_all_authenticated" on public.lead_etiquetas;
create policy "lead_etiquetas_all_authenticated"
  on public.lead_etiquetas for all
  to authenticated
  using (true)
  with check (true);


-- ===== 0004_historico_estagio.sql =====

-- EazyClick CRM — histórico de movimentações de estágio do lead (exibido no drawer do Pipeline).

create table if not exists public.lead_historico_estagio (
  id bigserial primary key,
  id_lead int4 not null references public."BASE_DE_LEADS"(id) on delete cascade,
  estagio_anterior text,
  estagio_novo text not null,
  usuario text,
  created_at timestamptz default now()
);

alter table public.lead_historico_estagio enable row level security;

drop policy if exists "lead_historico_estagio_all_authenticated" on public.lead_historico_estagio;
create policy "lead_historico_estagio_all_authenticated"
  on public.lead_historico_estagio for all
  to authenticated
  using (true)
  with check (true);


-- ===== 0005_cargos_e_fila_vendedor.sql =====

-- EazyClick CRM — ajustes de cargos e regras de acesso por vendedor.
--
-- 1) Nova role "admin" (administrador do sistema, acesso total de visualização), distinta de
--    "admin_master" (role oculta, senha padrão interna dos desenvolvedores, nunca criável pela UI).
-- 2) Todo vendedor criado pelo sistema entra automaticamente na fila de atendimento como "espera".
-- 3) RLS de BASE_DE_LEADS: admin_master/admin/gerente veem todos os leads; vendedor só vê os
--    leads cuja coluna "vendedor" (texto) é igual ao seu próprio nome em profiles.

alter table public.profiles drop constraint if exists profiles_cargo_check;
alter table public.profiles
  add constraint profiles_cargo_check
  check (cargo in ('admin_master', 'admin', 'gerente', 'vendedor'));

create or replace function public.get_my_nome()
returns text
language sql
security definer
set search_path = public
stable
as $$
  select nome from public.profiles where id = auth.uid();
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cargo text;
begin
  v_cargo := coalesce(new.raw_user_meta_data->>'cargo', 'vendedor');

  insert into public.profiles (id, nome, email, cargo)
  values (
    new.id,
    new.raw_user_meta_data->>'nome',
    new.email,
    v_cargo
  );

  if v_cargo = 'vendedor' then
    insert into public."VENDEDORES" (vendedor, telefone, id_empresa, quantos_lead, atender)
    values (
      new.raw_user_meta_data->>'nome',
      new.raw_user_meta_data->>'telefone',
      null,
      0,
      'espera'
    );
  end if;

  return new;
end;
$$;

drop policy if exists "base_de_leads_all_authenticated" on public."BASE_DE_LEADS";

drop policy if exists "base_de_leads_select" on public."BASE_DE_LEADS";
create policy "base_de_leads_select"
  on public."BASE_DE_LEADS" for select
  to authenticated
  using (
    public.get_my_cargo() in ('admin_master', 'admin', 'gerente')
    or vendedor = public.get_my_nome()
  );

drop policy if exists "base_de_leads_insert" on public."BASE_DE_LEADS";
create policy "base_de_leads_insert"
  on public."BASE_DE_LEADS" for insert
  to authenticated
  with check (true);

drop policy if exists "base_de_leads_update" on public."BASE_DE_LEADS";
create policy "base_de_leads_update"
  on public."BASE_DE_LEADS" for update
  to authenticated
  using (
    public.get_my_cargo() in ('admin_master', 'admin', 'gerente')
    or vendedor = public.get_my_nome()
  )
  with check (
    public.get_my_cargo() in ('admin_master', 'admin', 'gerente')
    or vendedor = public.get_my_nome()
  );

drop policy if exists "base_de_leads_delete" on public."BASE_DE_LEADS";
create policy "base_de_leads_delete"
  on public."BASE_DE_LEADS" for delete
  to authenticated
  using (public.get_my_cargo() in ('admin_master', 'admin', 'gerente'));


-- ===== 0006_status_usuario_e_admin_role.sql =====

-- EazyClick CRM — status de ativação do usuário e inclusão da role "admin" nas policies de
-- profiles (a role foi criada na migration anterior, mas a policy de update ainda só liberava
-- admin_master/gerente, impedindo um "admin" de alterar cargo de outros usuários).

alter table public.profiles
  add column if not exists desativado boolean not null default false;

drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin"
  on public.profiles for update
  to authenticated
  using (
    id = auth.uid()
    or public.get_my_cargo() in ('admin_master', 'admin', 'gerente')
  );


-- ===== 0007_branding_e_logo.sql =====

-- EazyClick CRM — branding por cliente: logo e cores do sistema.
--
-- A tabela app_settings já guarda o token da uazapi (sensível, só admin_master pode ler/gravar).
-- Logo/cores precisam ser lidas por TODO usuário (inclusive antes do login, na tela de login),
-- então em vez de abrir o SELECT de app_settings para todo mundo (o que exporia o token da
-- uazapi), criamos uma função SECURITY DEFINER que expõe só as colunas de branding.

alter table public.app_settings
  add column if not exists logo_url text,
  add column if not exists cor_primaria text not null default '#111827',
  add column if not exists cor_secundaria text not null default '#3b82f6',
  add column if not exists cor_texto text not null default '#111827',
  add column if not exists cor_fundo text not null default '#f5f6f8';

create or replace function public.get_branding()
returns table (
  logo_url text,
  cor_primaria text,
  cor_secundaria text,
  cor_texto text,
  cor_fundo text
)
language sql
security definer
set search_path = public
stable
as $$
  select logo_url, cor_primaria, cor_secundaria, cor_texto, cor_fundo
  from public.app_settings
  where id = 1;
$$;

grant execute on function public.get_branding() to anon, authenticated;

-- Bucket público para os arquivos de logo. Upload/troca restrito a admin_master; leitura
-- pública (a logo aparece na sidebar e tela de login para todos, inclusive sem sessão).
insert into storage.buckets (id, name, public)
values ('logos', 'logos', true)
on conflict (id) do nothing;

drop policy if exists "logos_public_read" on storage.objects;
create policy "logos_public_read"
  on storage.objects for select
  using (bucket_id = 'logos');

drop policy if exists "logos_admin_master_insert" on storage.objects;
create policy "logos_admin_master_insert"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'logos' and public.get_my_cargo() = 'admin_master');

drop policy if exists "logos_admin_master_update" on storage.objects;
create policy "logos_admin_master_update"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'logos' and public.get_my_cargo() = 'admin_master');

drop policy if exists "logos_admin_master_delete" on storage.objects;
create policy "logos_admin_master_delete"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'logos' and public.get_my_cargo() = 'admin_master');


-- ===== 0008_timer_negociacao.sql =====

-- EazyClick CRM — cronômetro de 30 minutos para leads em "Em Negociação".
--
-- Quando um lead entra em "em_negociacao", o app grava negociacao_expira_em (agora + 30min).
-- Ao expirar, o n8n (via polling externo no Supabase) dispara a notificação de WhatsApp
-- para o vendedor e o app exibe um popup para quem estiver com o lead visível.
-- Gerente/Admin podem estender o prazo em +30min a partir do popup; essa extensão é
-- restrita por role diretamente no banco (trigger abaixo), pois a RLS de UPDATE em
-- BASE_DE_LEADS permite que o próprio vendedor edite o seu lead.

alter table public."BASE_DE_LEADS"
  add column if not exists negociacao_expira_em timestamptz,
  add column if not exists negociacao_notificado_em timestamptz,
  add column if not exists negociacao_extensoes int not null default 0;

create or replace function public.checar_extensao_negociacao()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.negociacao_extensoes > old.negociacao_extensoes
     and public.get_my_cargo() not in ('admin_master', 'admin', 'gerente') then
    raise exception 'Apenas gerente ou admin podem estender o cronômetro de negociação.';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_checar_extensao_negociacao on public."BASE_DE_LEADS";
create trigger trg_checar_extensao_negociacao
  before update on public."BASE_DE_LEADS"
  for each row
  execute function public.checar_extensao_negociacao();


-- ===== 0009_negociacao_notificacao_robusta.sql =====

-- EazyClick CRM — robustece o cronômetro de "Em Negociação" (0008_timer_negociacao.sql):
--
-- 1. Colunas para rastrear o envio da notificação ao webhook do n8n (WhatsApp), permitindo
--    retry sem duplicar o disparo mesmo com múltiplos navegadores/processos concorrentes
--    (painel flutuante do client + o cron externo em /api/negociacao/processar-vencidas).
-- 2. Function reivindicar_notificacao_negociacao(): UPDATE atômico que só uma chamada
--    concorrente consegue "ganhar" por lead, com destravamento automático de reivindicações
--    mortas (processo que reivindicou e morreu antes de concluir) após 2 minutos.

alter table public."BASE_DE_LEADS"
  add column if not exists negociacao_notificacao_status text
    check (negociacao_notificacao_status in ('enviando', 'erro', 'enviado')),
  add column if not exists negociacao_notificacao_tentativas int not null default 0,
  add column if not exists negociacao_notificacao_erro text,
  add column if not exists negociacao_notificacao_reivindicada_em timestamptz;

create or replace function public.reivindicar_notificacao_negociacao(p_lead_id bigint)
returns table (
  id bigint,
  nome_lead text,
  telefone text,
  vendedor text,
  negociacao_expira_em timestamptz,
  negociacao_notificacao_tentativas int
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  update public."BASE_DE_LEADS" as l
  set
    negociacao_notificacao_status = 'enviando',
    negociacao_notificacao_tentativas = l.negociacao_notificacao_tentativas + 1,
    negociacao_notificacao_reivindicada_em = now()
  where l.id = p_lead_id
    and l.estagio_lead = 'em_negociacao'
    and l.negociacao_expira_em is not null
    and l.negociacao_expira_em <= now()
    and l.negociacao_notificado_em is null
    and (
      l.negociacao_notificacao_status is null
      or l.negociacao_notificacao_status = 'erro'
      or l.negociacao_notificacao_reivindicada_em < now() - interval '2 minutes'
    )
  returning
    l.id, l.nome_lead, l.telefone, l.vendedor, l.negociacao_expira_em,
    l.negociacao_notificacao_tentativas;
end;
$$;

-- Só o service_role (usado pelas rotas server-side com createAdminClient) pode reivindicar
-- notificações — nunca o client autenticado direto, senão um vendedor poderia forjar o disparo
-- do webhook para qualquer lead vencido.
revoke execute on function public.reivindicar_notificacao_negociacao(bigint) from public;
revoke execute on function public.reivindicar_notificacao_negociacao(bigint) from anon;
revoke execute on function public.reivindicar_notificacao_negociacao(bigint) from authenticated;
grant execute on function public.reivindicar_notificacao_negociacao(bigint) to service_role;


-- ===== 0010_follow_manual.sql =====

-- EazyClick CRM - marcador simples para o scheduler de Follow-up no n8n.
-- O CRM grava "ativo" quando o lead entra em Follow-up e "inativo" quando sai.
-- O workflow agendado do n8n pode buscar BASE_DE_LEADS where follow_manual = 'ativo'.

alter table public."BASE_DE_LEADS"
  add column if not exists follow_manual text not null default 'inativo';

update public."BASE_DE_LEADS"
set follow_manual = case
  when lower(coalesce(estagio_lead, '')) = 'follow_up' then 'ativo'
  else 'inativo'
end;


-- ===== 0011_sync_follow_manual.sql =====

-- Mantem follow_manual sempre sincronizado com o estagio do lead.
-- Isso protege tambem alteracoes feitas fora do CRM, como automacoes n8n/webhooks.

create or replace function public.sync_follow_manual_from_estagio()
returns trigger
language plpgsql
as $$
begin
  new.follow_manual := case
    when lower(coalesce(new.estagio_lead, '')) = 'follow_up' then 'ativo'
    else 'inativo'
  end;

  return new;
end;
$$;

drop trigger if exists trg_sync_follow_manual_from_estagio on public."BASE_DE_LEADS";

create trigger trg_sync_follow_manual_from_estagio
  before insert or update of estagio_lead on public."BASE_DE_LEADS"
  for each row
  execute function public.sync_follow_manual_from_estagio();

update public."BASE_DE_LEADS"
set follow_manual = case
  when lower(coalesce(estagio_lead, '')) = 'follow_up' then 'ativo'
  else 'inativo'
end
where follow_manual is distinct from case
  when lower(coalesce(estagio_lead, '')) = 'follow_up' then 'ativo'
  else 'inativo'
end;


-- ===== 0012_pipeline_etapas_configuraveis.sql =====

-- Etapas configuraveis do pipeline (instalacao single-tenant).
create table if not exists public.pipeline_etapas (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  nome text not null,
  cor text not null,
  ordem integer not null,
  is_inicial boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pipeline_etapas_slug_check check (slug ~ '^[a-z0-9]+(?:_[a-z0-9]+)*$' and length(slug) <= 60),
  constraint pipeline_etapas_nome_check check (length(btrim(nome)) between 1 and 60),
  constraint pipeline_etapas_cor_check check (cor ~ '^#[0-9A-Fa-f]{6}$'),
  constraint pipeline_etapas_ordem_check check (ordem >= 0),
  constraint pipeline_etapas_ordem_key unique (ordem) deferrable initially immediate
);

create unique index if not exists pipeline_etapas_apenas_uma_inicial
  on public.pipeline_etapas (is_inicial) where is_inicial;

insert into public.pipeline_etapas (slug, nome, cor, ordem, is_inicial) values
  ('oportunidade', 'Oportunidade', '#22c55e', 0, true),
  ('em_qualificacao', 'Em Qualificacao', '#38bdf8', 1, false),
  ('em_negociacao', 'Em Negociacao', '#f97316', 2, false),
  ('follow_up', 'Follow-up', '#a855f7', 3, false),
  ('fechado', 'Fechado', '#16a34a', 4, false),
  ('nao_fechou', 'Nao Fechou', '#ef4444', 5, false),
  ('pesquisa_atendimento', 'Lembrete Interno', '#06b6d4', 6, false)
on conflict (slug) do nothing;

grant select, insert, update, delete on public.pipeline_etapas to authenticated;
grant usage, select on sequence public.pipeline_etapas_id_seq to authenticated;

create or replace function public.pipeline_etapas_set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at := now(); return new; end; $$;
drop trigger if exists trg_pipeline_etapas_updated_at on public.pipeline_etapas;
create trigger trg_pipeline_etapas_updated_at before update on public.pipeline_etapas
for each row execute function public.pipeline_etapas_set_updated_at();

create or replace function public.pipeline_etapa_protegida(p_slug text)
returns boolean language sql immutable as $$
  select p_slug in ('oportunidade','em_qualificacao','em_negociacao','follow_up');
$$;

create or replace function public.bloquear_alteracao_etapa_protegida()
returns trigger language plpgsql set search_path = public as $$
begin
  if public.pipeline_etapa_protegida(old.slug) and (
    new.slug is distinct from old.slug
    or new.nome is distinct from old.nome
    or new.cor is distinct from old.cor
    or new.ordem is distinct from old.ordem
    or new.is_inicial is distinct from old.is_inicial
  ) then
    raise exception 'Esta etapa e protegida por automacoes e nao pode ser alterada.' using errcode='42501';
  end if;
  return new;
end; $$;
drop trigger if exists trg_bloquear_alteracao_etapa_protegida on public.pipeline_etapas;
create trigger trg_bloquear_alteracao_etapa_protegida before update on public.pipeline_etapas
for each row execute function public.bloquear_alteracao_etapa_protegida();

-- Remove somente CHECK constraints que efetivamente mencionam estagio_lead.
do $$ declare r record;
begin
  for r in
    select c.conname from pg_constraint c
    join pg_class t on t.oid = c.conrelid join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public' and t.relname = 'BASE_DE_LEADS' and c.contype = 'c'
      and position('estagio_lead' in lower(pg_get_constraintdef(c.oid))) > 0
  loop execute format('alter table public."BASE_DE_LEADS" drop constraint %I', r.conname); end loop;
end $$;

create or replace function public.validar_estagio_lead()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.estagio_lead is null or not exists (
    select 1 from public.pipeline_etapas e where e.slug = new.estagio_lead
  ) then raise exception 'Etapa do pipeline inexistente: %', coalesce(new.estagio_lead, '(vazia)') using errcode='23503';
  end if;
  return new;
end; $$;
drop trigger if exists trg_validar_estagio_lead on public."BASE_DE_LEADS";
create trigger trg_validar_estagio_lead before insert or update of estagio_lead
on public."BASE_DE_LEADS" for each row execute function public.validar_estagio_lead();

create or replace function public.impedir_exclusao_etapa_em_uso()
returns trigger language plpgsql set search_path = public as $$
begin
  if public.pipeline_etapa_protegida(old.slug) then
    raise exception 'Esta etapa e protegida por automacoes e nao pode ser excluida.' using errcode='42501';
  end if;
  if exists (select 1 from public."BASE_DE_LEADS" where estagio_lead = old.slug) then
    raise exception 'Esta etapa possui leads. Mova-os antes de excluir.' using errcode='23503';
  end if;
  if old.is_inicial then raise exception 'Defina outra etapa inicial antes de excluir esta etapa.'; end if;
  return old;
end; $$;
drop trigger if exists trg_impedir_exclusao_etapa_em_uso on public.pipeline_etapas;
create trigger trg_impedir_exclusao_etapa_em_uso before delete on public.pipeline_etapas
for each row execute function public.impedir_exclusao_etapa_em_uso();

create or replace function public.reordenar_pipeline_etapas(p_ids bigint[])
returns void language plpgsql security definer set search_path = public as $$
declare v_total integer;
begin
  if public.get_my_cargo() not in ('admin_master','admin','gerente') then raise exception 'Sem permissao para reordenar etapas.' using errcode='42501'; end if;
  select count(*) into v_total from public.pipeline_etapas;
  if cardinality(p_ids) <> v_total or (select count(distinct x) from unnest(p_ids) x) <> v_total
    or exists (select 1 from unnest(p_ids) x where not exists (select 1 from public.pipeline_etapas e where e.id=x))
  then raise exception 'A sequencia deve conter todas as etapas exatamente uma vez.'; end if;
  set constraints pipeline_etapas_ordem_key deferred;
  update public.pipeline_etapas e set ordem = u.ordem - 1
  from unnest(p_ids) with ordinality u(id, ordem) where e.id=u.id;
end; $$;
revoke execute on function public.reordenar_pipeline_etapas(bigint[]) from public, anon;
grant execute on function public.reordenar_pipeline_etapas(bigint[]) to authenticated;

alter table public.pipeline_etapas enable row level security;
drop policy if exists "pipeline_etapas_select" on public.pipeline_etapas;
create policy "pipeline_etapas_select" on public.pipeline_etapas for select to authenticated using (true);
drop policy if exists "pipeline_etapas_insert" on public.pipeline_etapas;
create policy "pipeline_etapas_insert" on public.pipeline_etapas for insert to authenticated with check (public.get_my_cargo() in ('admin_master','admin','gerente'));
drop policy if exists "pipeline_etapas_update" on public.pipeline_etapas;
create policy "pipeline_etapas_update" on public.pipeline_etapas for update to authenticated using (public.get_my_cargo() in ('admin_master','admin','gerente')) with check (public.get_my_cargo() in ('admin_master','admin','gerente'));
drop policy if exists "pipeline_etapas_delete" on public.pipeline_etapas;
create policy "pipeline_etapas_delete" on public.pipeline_etapas for delete to authenticated using (public.get_my_cargo() in ('admin_master','admin','gerente'));


-- ===== 0013_follow_up_bom_dia_para_resgate.sql =====

-- Move para Resgate o lead em Follow-up que ja recebeu a mensagem de sistema "bom dia".
-- O historico de chat e relacionado ao telefone do lead pelo session_id.

insert into public.pipeline_etapas (slug, nome, cor, ordem, is_inicial)
select
  'resgate',
  'Resgate',
  '#eab308',
  coalesce(max(ordem), -1) + 1,
  false
from public.pipeline_etapas
on conflict (slug) do nothing;

create or replace function public.mover_follow_up_bom_dia_para_resgate()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.session_id is not null
    and new.message ->> 'type' = 'system'
    and new.message ->> 'content' in ('bom dia', 'Bom dia')
  then
    update public."BASE_DE_LEADS" as l
    set estagio_lead = 'resgate'
    where regexp_replace(coalesce(l.telefone, ''), '[^0-9]', '', 'g') <> ''
      and regexp_replace(l.telefone, '[^0-9]', '', 'g') =
          regexp_replace(new.session_id::text, '[^0-9]', '', 'g')
      and l.estagio_lead = 'follow_up'
      and lower(coalesce(l.follow_manual::text, '')) = 'ativo'
      and lower(coalesce(l.ja_recebeu_msg::text, '')) = 'sim';
  end if;

  return new;
end;
$$;

revoke all on function public.mover_follow_up_bom_dia_para_resgate() from public;

drop trigger if exists trg_mover_follow_up_bom_dia_para_resgate
  on public."HISTORICO_CHAT";

create trigger trg_mover_follow_up_bom_dia_para_resgate
  after insert or update of message, session_id
  on public."HISTORICO_CHAT"
  for each row
  execute function public.mover_follow_up_bom_dia_para_resgate();

-- Processa tambem leads que ja satisfaziam a regra antes da criacao do trigger.
update public."BASE_DE_LEADS" as l
set estagio_lead = 'resgate'
where l.estagio_lead = 'follow_up'
  and lower(coalesce(l.follow_manual::text, '')) = 'ativo'
  and lower(coalesce(l.ja_recebeu_msg::text, '')) = 'sim'
  and regexp_replace(coalesce(l.telefone, ''), '[^0-9]', '', 'g') <> ''
  and exists (
    select 1
    from public."HISTORICO_CHAT" as h
    where h.session_id is not null
      and regexp_replace(h.session_id::text, '[^0-9]', '', 'g') =
          regexp_replace(l.telefone, '[^0-9]', '', 'g')
      and h.message ->> 'type' = 'system'
      and h.message ->> 'content' in ('bom dia', 'Bom dia')
  );


-- ===== 0014_etiquetas_na_base_de_leads.sql =====

-- Expõe, na própria BASE_DE_LEADS, a lista de IDs das etiquetas atribuídas.
-- lead_etiquetas permanece como relação normalizada e é sincronizada nos dois sentidos.

alter table public."BASE_DE_LEADS"
  add column if not exists etiquetas bigint[] not null default '{}'::bigint[];

-- Importa os vínculos que já existiam antes da criação da coluna.
update public."BASE_DE_LEADS" as l
set etiquetas = coalesce(
  (
    select array_agg(le.id_etiqueta order by le.id_etiqueta)
    from public.lead_etiquetas le
    where le.id_lead = l.id
  ),
  '{}'::bigint[]
);

create or replace function public.normalizar_e_validar_etiquetas_do_lead()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  id_inexistente bigint;
begin
  select array_agg(ids.id_etiqueta order by ids.id_etiqueta)
  into new.etiquetas
  from (
    select distinct id_etiqueta
    from unnest(coalesce(new.etiquetas, '{}'::bigint[])) as u(id_etiqueta)
    where id_etiqueta is not null
  ) as ids;

  new.etiquetas := coalesce(new.etiquetas, '{}'::bigint[]);

  select ids.id_etiqueta
  into id_inexistente
  from unnest(coalesce(new.etiquetas, '{}'::bigint[])) as ids(id_etiqueta)
  left join public.etiquetas e on e.id = ids.id_etiqueta
  where e.id is null
  limit 1;

  if id_inexistente is not null then
    raise exception 'Etiqueta com ID % nao existe', id_inexistente
      using errcode = '23503';
  end if;

  return new;
end;
$$;

create or replace function public.sync_base_de_leads_etiquetas()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  delete from public.lead_etiquetas
  where id_lead = new.id
    and id_etiqueta <> all (new.etiquetas);

  insert into public.lead_etiquetas (id_lead, id_etiqueta)
  select new.id, id_etiqueta
  from unnest(new.etiquetas) as ids(id_etiqueta)
  on conflict (id_lead, id_etiqueta) do nothing;

  return new;
end;
$$;

create or replace function public.sync_lead_etiquetas_para_base()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  lead_id int4;
begin
  if tg_op = 'DELETE' then
    lead_id := old.id_lead;
  else
    lead_id := new.id_lead;
  end if;

  update public."BASE_DE_LEADS" as l
  set etiquetas = coalesce(
    (
      select array_agg(le.id_etiqueta order by le.id_etiqueta)
      from public.lead_etiquetas le
      where le.id_lead = lead_id
    ),
    '{}'::bigint[]
  )
  where l.id = lead_id;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_normalizar_etiquetas_do_lead on public."BASE_DE_LEADS";
create trigger trg_normalizar_etiquetas_do_lead
before insert or update of etiquetas on public."BASE_DE_LEADS"
for each row execute function public.normalizar_e_validar_etiquetas_do_lead();

drop trigger if exists trg_sync_base_de_leads_etiquetas on public."BASE_DE_LEADS";
create trigger trg_sync_base_de_leads_etiquetas
after insert or update of etiquetas on public."BASE_DE_LEADS"
for each row execute function public.sync_base_de_leads_etiquetas();

drop trigger if exists trg_sync_lead_etiquetas_para_base on public.lead_etiquetas;
create trigger trg_sync_lead_etiquetas_para_base
after insert or delete on public.lead_etiquetas
for each row execute function public.sync_lead_etiquetas_para_base();

comment on column public."BASE_DE_LEADS".etiquetas is
  'Lista de IDs de public.etiquetas; sincronizada automaticamente com public.lead_etiquetas.';


-- ===== 0015_lead_ia_e_protecao_cargo.sql =====

-- Controle transacional da IA por lead e proteção contra autoelevação de cargo.

do $$
declare
  v_tipo text;
  v_invalido text;
begin
  select data_type into v_tipo
  from information_schema.columns
  where table_schema = 'public' and table_name = 'BASE_DE_LEADS' and column_name = 'bot_ativo';

  if v_tipo is null then
    alter table public."BASE_DE_LEADS" add column bot_ativo boolean;
  elsif v_tipo <> 'boolean' then
    execute $query$
      select bot_ativo::text
      from public."BASE_DE_LEADS"
      where bot_ativo is not null
        and lower(trim(bot_ativo::text)) not in ('true', 'false', 'ativo', 'inativo', '1', '0')
      limit 1
    $query$ into v_invalido;

    if v_invalido is not null then
      raise exception 'Valor legado incompatível em BASE_DE_LEADS.bot_ativo.' using errcode = '22000';
    end if;

    alter table public."BASE_DE_LEADS" alter column bot_ativo drop default;
    alter table public."BASE_DE_LEADS"
      alter column bot_ativo type boolean
      using lower(trim(bot_ativo::text)) in ('true', 'ativo', '1');
  end if;
end;
$$;

update public."BASE_DE_LEADS"
set bot_ativo = false
where bot_ativo is null;

alter table public."BASE_DE_LEADS"
  alter column bot_ativo set default false,
  alter column bot_ativo set not null;

alter table public."BASE_DE_LEADS"
  add column if not exists bot_ativo_alterado_em timestamptz;

create or replace function public.registrar_alteracao_bot_ativo()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.bot_ativo is distinct from old.bot_ativo then
    new.bot_ativo_alterado_em := now();
  else
    new.bot_ativo_alterado_em := old.bot_ativo_alterado_em;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_registrar_alteracao_bot_ativo on public."BASE_DE_LEADS";
create trigger trg_registrar_alteracao_bot_ativo
  before update of bot_ativo, bot_ativo_alterado_em on public."BASE_DE_LEADS"
  for each row execute function public.registrar_alteracao_bot_ativo();

create or replace function public.proteger_alteracao_cargo()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.cargo is distinct from old.cargo then
    if auth.uid() = old.id then
      raise exception 'Não é permitido alterar o próprio cargo.' using errcode = '42501';
    end if;
    if coalesce(public.get_my_cargo(), '') not in ('admin_master', 'admin', 'gerente') then
      raise exception 'Sem permissão para alterar cargo.' using errcode = '42501';
    end if;
    if new.cargo = 'admin_master' and public.get_my_cargo() <> 'admin_master' then
      raise exception 'Somente admin_master pode atribuir esse cargo.' using errcode = '42501';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_proteger_alteracao_cargo on public.profiles;
create trigger trg_proteger_alteracao_cargo
  before update of cargo on public.profiles
  for each row execute function public.proteger_alteracao_cargo();


-- ===== 0016_auditoria_vendas_estoque.sql =====

-- Auditoria e integridade do CRM. Revisar backup e integrações n8n antes de aplicar.
alter table public."BASE_DE_LEADS"
  add column if not exists observacao_autor_id uuid,
  add column if not exists observacao_autor_nome text,
  add column if not exists observacao_atualizada_em timestamptz;

create table if not exists public.lead_logs (
  id bigint generated by default as identity primary key,
  id_lead int4 not null references public."BASE_DE_LEADS"(id) on delete cascade,
  acao text not null,
  responsavel_id uuid,
  responsavel_nome text not null default 'Sistema',
  detalhes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists lead_logs_lead_created_idx on public.lead_logs (id_lead, created_at desc);
alter table public.lead_logs enable row level security;
drop policy if exists "lead_logs_select_authenticated" on public.lead_logs;
create policy "lead_logs_select_authenticated" on public.lead_logs for select to authenticated using (true);
grant select on public.lead_logs to authenticated;
revoke insert, update, delete on public.lead_logs from authenticated, anon;

create or replace function public.audit_base_de_leads() returns trigger
language plpgsql security definer set search_path = public as $$
declare v_uid uuid := auth.uid(); v_nome text; v_acao text; v_id int4; v_detalhes jsonb;
begin
  select coalesce(nullif(btrim(nome), ''), email, 'Usuário desconhecido') into v_nome
  from public.profiles where id = v_uid;
  v_nome := coalesce(v_nome, 'Sistema');
  v_id := coalesce(new.id, old.id);
  v_acao := case when tg_op='INSERT' then 'lead_criado' when tg_op='DELETE' then 'lead_excluido' else 'lead_atualizado' end;
  v_detalhes := case when tg_op='INSERT' then jsonb_build_object('novo', to_jsonb(new) - array['senha','token'])
    when tg_op='DELETE' then jsonb_build_object('anterior', to_jsonb(old) - array['senha','token'])
    else jsonb_build_object('anterior', to_jsonb(old) - array['senha','token'], 'novo', to_jsonb(new) - array['senha','token']) end;
  insert into public.lead_logs(id_lead, acao, responsavel_id, responsavel_nome, detalhes)
  values(v_id, v_acao, v_uid, v_nome, v_detalhes);
  return coalesce(new, old);
end $$;
drop trigger if exists trg_audit_base_de_leads on public."BASE_DE_LEADS";
create trigger trg_audit_base_de_leads after insert or update on public."BASE_DE_LEADS"
for each row execute function public.audit_base_de_leads();

create or replace function public.audit_lead_etiquetas() returns trigger
language plpgsql security definer set search_path = public as $$
declare v_uid uuid := auth.uid(); v_nome text;
begin
  select coalesce(nullif(btrim(nome), ''), email, 'Usuário desconhecido') into v_nome
    from public.profiles where id=v_uid;
  insert into public.lead_logs(id_lead, acao, responsavel_id, responsavel_nome, detalhes)
  values(coalesce(new.id_lead, old.id_lead),
    case when tg_op='INSERT' then 'etiqueta_adicionada' else 'etiqueta_removida' end,
    v_uid, coalesce(v_nome, 'Sistema'),
    jsonb_build_object('id_etiqueta', coalesce(new.id_etiqueta, old.id_etiqueta)));
  return coalesce(new, old);
end $$;
drop trigger if exists trg_audit_lead_etiquetas on public.lead_etiquetas;
create trigger trg_audit_lead_etiquetas after insert or delete on public.lead_etiquetas
for each row execute function public.audit_lead_etiquetas();

create or replace function public.validar_venda_fechada() returns trigger
language plpgsql set search_path = public as $$
begin
  if new.estagio_lead = 'fechado' and (new.nome_lead is null or btrim(new.nome_lead) = '' or new.valor is null or new.valor <= 0) then
    raise exception 'Venda fechada exige nome e valor maior que zero.' using errcode='23514';
  end if;
  if tg_op = 'INSERT' or new.observacao_vendedor is distinct from old.observacao_vendedor then
    new.observacao_autor_id := auth.uid();
    select coalesce(nullif(btrim(nome),''), email, 'Usuário desconhecido') into new.observacao_autor_nome
      from public.profiles where id=auth.uid();
    new.observacao_autor_nome := coalesce(new.observacao_autor_nome, 'Sistema');
    new.observacao_atualizada_em := now();
  end if;
  return new;
end $$;
drop trigger if exists trg_validar_venda_fechada on public."BASE_DE_LEADS";
create trigger trg_validar_venda_fechada before insert or update on public."BASE_DE_LEADS"
for each row execute function public.validar_venda_fechada();

create or replace function public.fechar_venda(p_id_lead int4, p_nome text, p_valor numeric)
returns public."BASE_DE_LEADS" language plpgsql security invoker set search_path = public as $$
declare v_lead public."BASE_DE_LEADS";
begin
  update public."BASE_DE_LEADS" set nome_lead=btrim(p_nome), valor=p_valor, estagio_lead='fechado',
    follow_manual='inativo' where id=p_id_lead and id_empresa=1 returning * into v_lead;
  if v_lead.id is null then raise exception 'Lead não encontrado.'; end if;
  return v_lead;
end $$;
grant execute on function public.fechar_venda(int4,text,numeric) to authenticated;

update public."ESTOQUE" set status = translate(lower(btrim(status)), 'áàâãéêíóôõúç', 'aaaaeeiooouc')
where status is not null;
update public."ESTOQUE" set status='indisponivel' where status not in ('disponivel','indisponivel','vendido');
alter table public."ESTOQUE" alter column status set default 'disponivel';
do $$ begin
  if not exists(select 1 from pg_constraint where conname='estoque_status_canonico') then
    alter table public."ESTOQUE" add constraint estoque_status_canonico check (status in ('disponivel', 'indisponivel', 'vendido'));
  end if;
end $$;


-- ===== 0017_corrigir_auditoria_e_realtime.sql =====

-- Correções de segurança, retenção de auditoria e atualização em tempo real.
-- Esta migration não aplica o schema automaticamente fora do fluxo normal de migrations.

-- Auditoria precisa sobreviver à exclusão do lead.
do $$
declare
  v_constraint text;
begin
  for v_constraint in
    select conname
    from pg_constraint
    where conrelid = 'public.lead_logs'::regclass
      and contype = 'f'
      and confrelid = 'public."BASE_DE_LEADS"'::regclass
  loop
    execute format('alter table public.lead_logs drop constraint %I', v_constraint);
  end loop;
end $$;

drop policy if exists "lead_logs_select_authenticated" on public.lead_logs;
create policy "lead_logs_select_authenticated"
  on public.lead_logs for select to authenticated
  using (
    exists (
      select 1
      from public."BASE_DE_LEADS" lead
      where lead.id = lead_logs.id_lead
    )
    or public.get_my_cargo() in ('admin_master', 'admin', 'gerente')
  );

create or replace function public.audit_base_de_leads()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_nome text;
  v_acao text;
  v_id int4;
  v_detalhes jsonb := '{}'::jsonb;
  v_old jsonb;
  v_new jsonb;
begin
  if tg_op = 'DELETE' then v_id := old.id; else v_id := new.id; end if;
  select coalesce(nullif(btrim(nome), ''), email)
    into v_nome from public.profiles where id = v_uid;
  v_nome := coalesce(v_nome, case when v_uid is null then 'Sistema' else 'Usuário desconhecido' end);

  if tg_op = 'DELETE' then
    v_acao := 'lead_excluido';
    v_detalhes := jsonb_build_object('nome_lead', old.nome_lead);
  elsif tg_op = 'INSERT' then
    v_acao := 'lead_criado';
    v_detalhes := jsonb_build_object('nome_lead', new.nome_lead);
  else
    v_old := to_jsonb(old) - array['updated_at'];
    v_new := to_jsonb(new) - array['updated_at'];
    v_detalhes := (
      select jsonb_build_object(
        'campos_alterados', coalesce(jsonb_agg(chave), '[]'::jsonb),
        'antes', coalesce(jsonb_object_agg(chave, v_old -> chave), '{}'::jsonb),
        'depois', coalesce(jsonb_object_agg(chave, v_new -> chave), '{}'::jsonb)
      )
      from jsonb_object_keys(v_new) chave
      where v_old -> chave is distinct from v_new -> chave
    );
    if old.observacao_vendedor is distinct from new.observacao_vendedor then
      v_acao := case
        when nullif(btrim(coalesce(old.observacao_vendedor, '')), '') is null
          then 'observacao_adicionada'
        else 'observacao_alterada'
      end;
    elsif old.vendedor is distinct from new.vendedor then
      v_acao := 'lead_transferido';
    elsif old.estagio_lead is distinct from new.estagio_lead then
      v_acao := 'estagio_alterado';
    else
      v_acao := 'lead_atualizado';
    end if;
  end if;

  insert into public.lead_logs(id_lead, acao, responsavel_id, responsavel_nome, detalhes)
  values(v_id, v_acao, v_uid, v_nome, v_detalhes);
  if tg_op = 'DELETE' then return old; end if;
  return new;
end $$;

drop trigger if exists trg_audit_base_de_leads on public."BASE_DE_LEADS";
create trigger trg_audit_base_de_leads
  after insert or update or delete on public."BASE_DE_LEADS"
  for each row execute function public.audit_base_de_leads();

-- Não imponha constraint nova sobre status compartilhado sem validar todas as automações.
alter table public."ESTOQUE" drop constraint if exists estoque_status_canonico;

-- Realtime é o caminho principal; polling no client fica apenas como contingência.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'BASE_DE_LEADS'
  ) then
    alter publication supabase_realtime add table public."BASE_DE_LEADS";
  end if;
end $$;


-- ===== 0018_venda_vinculada_estoque.sql =====

-- CRM automotivo: vincula obrigatoriamente a venda ao estoque e conclui ambos atomicamente.
-- Aplicar uma única vez após a migration 0017. Não executada automaticamente por este arquivo.

alter table public."BASE_DE_LEADS"
  add column if not exists estoque_veiculo_id text;

create or replace function public.validar_venda_fechada()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if lower(btrim(coalesce(new.estagio_lead, ''))) = 'fechado'
     and (tg_op = 'INSERT' or old.estagio_lead is distinct from new.estagio_lead)
     and (
       nullif(btrim(coalesce(new.nome_lead, '')), '') is null
       or new.valor is null
       or new.valor <= 0
       or nullif(btrim(coalesce(new.estoque_veiculo_id, '')), '') is null
     )
  then
    raise exception 'Venda fechada exige nome, valor maior que zero e veículo do estoque.'
      using errcode = '23514';
  end if;

  if tg_op = 'INSERT' or new.observacao_vendedor is distinct from old.observacao_vendedor then
    new.observacao_autor_id := auth.uid();
    select coalesce(nullif(btrim(nome), ''), email, 'Usuário desconhecido')
      into new.observacao_autor_nome
      from public.profiles
      where id = auth.uid();
    new.observacao_autor_nome := coalesce(new.observacao_autor_nome, 'Sistema');
    new.observacao_atualizada_em := now();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_validar_venda_fechada on public."BASE_DE_LEADS";
create trigger trg_validar_venda_fechada
  before insert or update on public."BASE_DE_LEADS"
  for each row execute function public.validar_venda_fechada();

create or replace function public.fechar_venda_com_veiculo(
  p_id_lead int4,
  p_nome text,
  p_valor numeric,
  p_estoque_id text
)
returns public."BASE_DE_LEADS"
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lead public."BASE_DE_LEADS"%rowtype;
  v_resultado public."BASE_DE_LEADS"%rowtype;
  v_status text;
begin
  if auth.uid() is null then
    raise exception 'Não autenticado.' using errcode = '42501';
  end if;
  if nullif(btrim(coalesce(p_nome, '')), '') is null
     or p_valor is null
     or p_valor <= 0
     or nullif(btrim(coalesce(p_estoque_id, '')), '') is null
  then
    raise exception 'Nome, valor e veículo são obrigatórios.' using errcode = '22023';
  end if;

  select *
    into v_lead
    from public."BASE_DE_LEADS" lead
    where lead.id = p_id_lead
    for update;
  if not found then
    raise exception 'Lead não encontrado.' using errcode = 'P0002';
  end if;

  if coalesce(public.get_my_cargo(), '') not in ('admin_master', 'admin', 'gerente')
     and coalesce(lower(btrim(v_lead.vendedor)), '')
       <> coalesce(lower(btrim(public.get_my_nome())), '')
  then
    raise exception 'Sem permissão para fechar esta venda.' using errcode = '42501';
  end if;

  select status
    into v_status
    from public."ESTOQUE" estoque
    where estoque.id::text = p_estoque_id
    for update;
  if not found then
    raise exception 'Veículo não encontrado.' using errcode = 'P0002';
  end if;

  if translate(lower(btrim(coalesce(v_status, ''))),
      'áàâãéêíóôõúç', 'aaaaeeiooouc') <> 'disponivel'
  then
    raise exception 'O veículo selecionado não está disponível.' using errcode = '23514';
  end if;

  update public."ESTOQUE"
     set status = 'vendido', updated_at = now()
   where id::text = p_estoque_id;

  update public."BASE_DE_LEADS"
     set nome_lead = btrim(p_nome),
         valor = p_valor,
         estagio_lead = 'fechado',
         follow_manual = 'inativo',
         estoque_veiculo_id = p_estoque_id
   where id = p_id_lead
   returning * into v_resultado;

  return v_resultado;
end;
$$;

revoke all on function public.fechar_venda_com_veiculo(int4, text, numeric, text)
  from public, anon;
grant execute on function public.fechar_venda_com_veiculo(int4, text, numeric, text)
  to authenticated;

notify pgrst, 'reload schema';
