-- Etapas configuraveis do pipeline (instalacao single-tenant).
create table if not exists public.pipeline_etapas (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  nome text not null,
  cor text not null,
  ordem integer not null,
  is_inicial boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pipeline_etapas_slug_check check (slug ~ '^[a-z0-9]+(?:_[a-z0-9]+)*$' and length(slug) <= 60),
  constraint pipeline_etapas_nome_check check (length(btrim(nome)) between 1 and 60),
  constraint pipeline_etapas_cor_check check (cor ~ '^#[0-9A-Fa-f]{6}$'),
  constraint pipeline_etapas_ordem_check check (ordem >= 0),
  constraint pipeline_etapas_ordem_key unique (ordem) deferrable initially immediate
);

create unique index if not exists pipeline_etapas_apenas_uma_inicial
  on public.pipeline_etapas (is_inicial) where is_inicial;

insert into public.pipeline_etapas (slug, nome, cor, ordem, is_inicial) values
  ('oportunidade', 'Oportunidade', '#22c55e', 0, true),
  ('em_qualificacao', 'Em Qualificacao', '#38bdf8', 1, false),
  ('em_negociacao', 'Em Negociacao', '#f97316', 2, false),
  ('follow_up', 'Follow-up', '#a855f7', 3, false),
  ('fechado', 'Fechado', '#16a34a', 4, false),
  ('nao_fechou', 'Nao Fechou', '#ef4444', 5, false),
  ('pesquisa_atendimento', 'Lembrete Interno', '#06b6d4', 6, false)
on conflict (slug) do nothing;

grant select, insert, update, delete on public.pipeline_etapas to authenticated;
grant usage, select on sequence public.pipeline_etapas_id_seq to authenticated;

create or replace function public.pipeline_etapas_set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at := now(); return new; end; $$;
drop trigger if exists trg_pipeline_etapas_updated_at on public.pipeline_etapas;
create trigger trg_pipeline_etapas_updated_at before update on public.pipeline_etapas
for each row execute function public.pipeline_etapas_set_updated_at();

create or replace function public.pipeline_etapa_protegida(p_slug text)
returns boolean language sql immutable as $$
  select p_slug in ('oportunidade','em_qualificacao','em_negociacao','follow_up');
$$;

create or replace function public.bloquear_alteracao_etapa_protegida()
returns trigger language plpgsql set search_path = public as $$
begin
  if public.pipeline_etapa_protegida(old.slug) and (
    new.slug is distinct from old.slug
    or new.nome is distinct from old.nome
    or new.cor is distinct from old.cor
    or new.ordem is distinct from old.ordem
    or new.is_inicial is distinct from old.is_inicial
  ) then
    raise exception 'Esta etapa e protegida por automacoes e nao pode ser alterada.' using errcode='42501';
  end if;
  return new;
end; $$;
drop trigger if exists trg_bloquear_alteracao_etapa_protegida on public.pipeline_etapas;
create trigger trg_bloquear_alteracao_etapa_protegida before update on public.pipeline_etapas
for each row execute function public.bloquear_alteracao_etapa_protegida();

-- Remove somente CHECK constraints que efetivamente mencionam estagio_lead.
do $$ declare r record;
begin
  for r in
    select c.conname from pg_constraint c
    join pg_class t on t.oid = c.conrelid join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public' and t.relname = 'BASE_DE_LEADS' and c.contype = 'c'
      and position('estagio_lead' in lower(pg_get_constraintdef(c.oid))) > 0
  loop execute format('alter table public."BASE_DE_LEADS" drop constraint %I', r.conname); end loop;
end $$;

create or replace function public.validar_estagio_lead()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.estagio_lead is null or not exists (
    select 1 from public.pipeline_etapas e where e.slug = new.estagio_lead
  ) then raise exception 'Etapa do pipeline inexistente: %', coalesce(new.estagio_lead, '(vazia)') using errcode='23503';
  end if;
  return new;
end; $$;
drop trigger if exists trg_validar_estagio_lead on public."BASE_DE_LEADS";
create trigger trg_validar_estagio_lead before insert or update of estagio_lead
on public."BASE_DE_LEADS" for each row execute function public.validar_estagio_lead();

create or replace function public.impedir_exclusao_etapa_em_uso()
returns trigger language plpgsql set search_path = public as $$
begin
  if public.pipeline_etapa_protegida(old.slug) then
    raise exception 'Esta etapa e protegida por automacoes e nao pode ser excluida.' using errcode='42501';
  end if;
  if exists (select 1 from public."BASE_DE_LEADS" where estagio_lead = old.slug) then
    raise exception 'Esta etapa possui leads. Mova-os antes de excluir.' using errcode='23503';
  end if;
  if old.is_inicial then raise exception 'Defina outra etapa inicial antes de excluir esta etapa.'; end if;
  return old;
end; $$;
drop trigger if exists trg_impedir_exclusao_etapa_em_uso on public.pipeline_etapas;
create trigger trg_impedir_exclusao_etapa_em_uso before delete on public.pipeline_etapas
for each row execute function public.impedir_exclusao_etapa_em_uso();

create or replace function public.reordenar_pipeline_etapas(p_ids bigint[])
returns void language plpgsql security definer set search_path = public as $$
declare v_total integer;
begin
  if public.get_my_cargo() not in ('admin_master','admin','gerente') then raise exception 'Sem permissao para reordenar etapas.' using errcode='42501'; end if;
  select count(*) into v_total from public.pipeline_etapas;
  if cardinality(p_ids) <> v_total or (select count(distinct x) from unnest(p_ids) x) <> v_total
    or exists (select 1 from unnest(p_ids) x where not exists (select 1 from public.pipeline_etapas e where e.id=x))
  then raise exception 'A sequencia deve conter todas as etapas exatamente uma vez.'; end if;
  set constraints pipeline_etapas_ordem_key deferred;
  update public.pipeline_etapas e set ordem = u.ordem - 1
  from unnest(p_ids) with ordinality u(id, ordem) where e.id=u.id;
end; $$;
revoke execute on function public.reordenar_pipeline_etapas(bigint[]) from public, anon;
grant execute on function public.reordenar_pipeline_etapas(bigint[]) to authenticated;

alter table public.pipeline_etapas enable row level security;
drop policy if exists "pipeline_etapas_select" on public.pipeline_etapas;
create policy "pipeline_etapas_select" on public.pipeline_etapas for select to authenticated using (true);
drop policy if exists "pipeline_etapas_insert" on public.pipeline_etapas;
create policy "pipeline_etapas_insert" on public.pipeline_etapas for insert to authenticated with check (public.get_my_cargo() in ('admin_master','admin','gerente'));
drop policy if exists "pipeline_etapas_update" on public.pipeline_etapas;
create policy "pipeline_etapas_update" on public.pipeline_etapas for update to authenticated using (public.get_my_cargo() in ('admin_master','admin','gerente')) with check (public.get_my_cargo() in ('admin_master','admin','gerente'));
drop policy if exists "pipeline_etapas_delete" on public.pipeline_etapas;
create policy "pipeline_etapas_delete" on public.pipeline_etapas for delete to authenticated using (public.get_my_cargo() in ('admin_master','admin','gerente'));
