-- Auditoria e integridade do CRM. Revisar backup e integrações n8n antes de aplicar.
alter table public."BASE_DE_LEADS"
  add column if not exists observacao_autor_id uuid,
  add column if not exists observacao_autor_nome text,
  add column if not exists observacao_atualizada_em timestamptz;

create table if not exists public.lead_logs (
  id bigint generated by default as identity primary key,
  id_lead int4 not null references public."BASE_DE_LEADS"(id) on delete cascade,
  acao text not null,
  responsavel_id uuid,
  responsavel_nome text not null default 'Sistema',
  detalhes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists lead_logs_lead_created_idx on public.lead_logs (id_lead, created_at desc);
alter table public.lead_logs enable row level security;
drop policy if exists "lead_logs_select_authenticated" on public.lead_logs;
create policy "lead_logs_select_authenticated" on public.lead_logs for select to authenticated using (true);
grant select on public.lead_logs to authenticated;
revoke insert, update, delete on public.lead_logs from authenticated, anon;

create or replace function public.audit_base_de_leads() returns trigger
language plpgsql security definer set search_path = public as $$
declare v_uid uuid := auth.uid(); v_nome text; v_acao text; v_id int4; v_detalhes jsonb;
begin
  select coalesce(nullif(btrim(nome), ''), email, 'Usuário desconhecido') into v_nome
  from public.profiles where id = v_uid;
  v_nome := coalesce(v_nome, 'Sistema');
  v_id := coalesce(new.id, old.id);
  v_acao := case when tg_op='INSERT' then 'lead_criado' when tg_op='DELETE' then 'lead_excluido' else 'lead_atualizado' end;
  v_detalhes := case when tg_op='INSERT' then jsonb_build_object('novo', to_jsonb(new) - array['senha','token'])
    when tg_op='DELETE' then jsonb_build_object('anterior', to_jsonb(old) - array['senha','token'])
    else jsonb_build_object('anterior', to_jsonb(old) - array['senha','token'], 'novo', to_jsonb(new) - array['senha','token']) end;
  insert into public.lead_logs(id_lead, acao, responsavel_id, responsavel_nome, detalhes)
  values(v_id, v_acao, v_uid, v_nome, v_detalhes);
  return coalesce(new, old);
end $$;
drop trigger if exists trg_audit_base_de_leads on public."BASE_DE_LEADS";
create trigger trg_audit_base_de_leads after insert or update on public."BASE_DE_LEADS"
for each row execute function public.audit_base_de_leads();

create or replace function public.audit_lead_etiquetas() returns trigger
language plpgsql security definer set search_path = public as $$
declare v_uid uuid := auth.uid(); v_nome text;
begin
  select coalesce(nullif(btrim(nome), ''), email, 'Usuário desconhecido') into v_nome
    from public.profiles where id=v_uid;
  insert into public.lead_logs(id_lead, acao, responsavel_id, responsavel_nome, detalhes)
  values(coalesce(new.id_lead, old.id_lead),
    case when tg_op='INSERT' then 'etiqueta_adicionada' else 'etiqueta_removida' end,
    v_uid, coalesce(v_nome, 'Sistema'),
    jsonb_build_object('id_etiqueta', coalesce(new.id_etiqueta, old.id_etiqueta)));
  return coalesce(new, old);
end $$;
drop trigger if exists trg_audit_lead_etiquetas on public.lead_etiquetas;
create trigger trg_audit_lead_etiquetas after insert or delete on public.lead_etiquetas
for each row execute function public.audit_lead_etiquetas();

create or replace function public.validar_venda_fechada() returns trigger
language plpgsql set search_path = public as $$
begin
  if new.estagio_lead = 'fechado' and (new.nome_lead is null or btrim(new.nome_lead) = '' or new.valor is null or new.valor <= 0) then
    raise exception 'Venda fechada exige nome e valor maior que zero.' using errcode='23514';
  end if;
  if tg_op = 'INSERT' or new.observacao_vendedor is distinct from old.observacao_vendedor then
    new.observacao_autor_id := auth.uid();
    select coalesce(nullif(btrim(nome),''), email, 'Usuário desconhecido') into new.observacao_autor_nome
      from public.profiles where id=auth.uid();
    new.observacao_autor_nome := coalesce(new.observacao_autor_nome, 'Sistema');
    new.observacao_atualizada_em := now();
  end if;
  return new;
end $$;
drop trigger if exists trg_validar_venda_fechada on public."BASE_DE_LEADS";
create trigger trg_validar_venda_fechada before insert or update on public."BASE_DE_LEADS"
for each row execute function public.validar_venda_fechada();

create or replace function public.fechar_venda(p_id_lead int4, p_nome text, p_valor numeric)
returns public."BASE_DE_LEADS" language plpgsql security invoker set search_path = public as $$
declare v_lead public."BASE_DE_LEADS";
begin
  update public."BASE_DE_LEADS" set nome_lead=btrim(p_nome), valor=p_valor, estagio_lead='fechado',
    follow_manual='inativo' where id=p_id_lead and id_empresa=1 returning * into v_lead;
  if v_lead.id is null then raise exception 'Lead não encontrado.'; end if;
  return v_lead;
end $$;
grant execute on function public.fechar_venda(int4,text,numeric) to authenticated;

update public."ESTOQUE" set status = translate(lower(btrim(status)), 'áàâãéêíóôõúç', 'aaaaeeiooouc')
where status is not null;
update public."ESTOQUE" set status='indisponivel' where status not in ('disponivel','indisponivel','vendido');
alter table public."ESTOQUE" alter column status set default 'disponivel';
do $$ begin
  if not exists(select 1 from pg_constraint where conname='estoque_status_canonico') then
    alter table public."ESTOQUE" add constraint estoque_status_canonico check (status in ('disponivel', 'indisponivel', 'vendido'));
  end if;
end $$;
